# Configuration for classifier


classifier:
  model:
    # Model weight path
    checkpoint: weights/70k_0.84.ckpt

    # Use half-precision (float16) instead of float32 for inference
    half: true

    # TorchDynamo, the latest method to speed up PyTorch code
    dynamo: true

  # Size of image for the inference
  image_size: 224
