# Configuration for detection


video:
  # Path to video
  path: ???

  # Video speed multiplied
  speed: 1

  # Frame delay (millisecond)
  delay: 1

  # Video resolution
  resolution: [ 1280, 720 ]

  # Save output
  save:
    # Save path and name
    save_path: records/
    save_name: output

    # Output resolution
    resolution: [ 1024, 576 ]
