# Configuration for detection


video:
  # Path to video
  path: ???

  # Video speed multiplying
  speed: 1

  # Frame delay (millisecond)
  delay: 1

  # Video resolution
  resolution: null

# Save output
record:
  # Save path
  save_path: records/

  # Save name
  save_name: output

  # Custom fps (null for auto)
  fps: null

  # Output resolution
  resolution: null
