# Configuration for density heatmap


heatmap:
  # Grow value
  grow: 3

  # Decay value
  decay: 1

  # Soften the layer
  blur: 0.8

  # Layer opacity
  alpha: 0.5

  # Save output
  save:
    # Write video
    video: true

    # Write an average image
    image: true

    # Save path and name
    save_path: records/
    save_name: heatmap

    # Output resolution
    resolution: [ 1280, 720 ]
