# Configuration for density heatmap


heatmap:
  # Layer config
  layer:
    # Grow value
    grow_value: 3

    # Decay value
    decay_value: 1

    # Soften the layer
    blurriness: 0.8

    # Layer opacity
    alpha: 0.5

  # Save output
  save:
    # Write video
    video: true

    # Write an average image
    image: true

    # Save path
    save_path: records/

    # Save name
    save_name: heatmap

    # Output resolution
    resolution: [ 1280, 720 ]
