# Configuration for human counting


human_count:
  # Increasing the value makes the output more stable but the response is slower
  smoothness: 10

  # Save output
  save:
    # Save path and name
    save_path: records/
    save_name: human_count

    # Frequency (second)
    interval: 1
