# Configuration for run.py


# GPU or CPU
device: auto

# Video configuration
video:
  # Path to video
  path: ...
  # Frame speed
  sampling: 2
  # Frame delay (millisecond)
  delay: 1
  # Human image process size
  image_size: 224
  # Write output
  save_output:
    enable: true
    save_path: records/
    save_name: output

# Human detection
detector:
  weight: weights/yolov8x.pt
  conf: 0.25
  iou: 0.3
  add_border: true

# Human activity classification
classifier:
  enable: false
  checkpoint: logs/epoch=23-step=1344.ckpt

# Feature options
feature:
  # Human bounding box
  human_box: true

  # Human middle dot
  human_dot: true

  # Count total person
  person_count:
    enable: true
    smoothness: 10
    save_output:
      enable: true
      # save frequency (second)
      interval: 1

  # Heatmap
  heatmap:
    enable: true
    grow: 3
    decay: 1
    blur: 0.8
    alpha: 0.5
    save:
      video: true
      image: true
      save_path: records/
      save_name: heatmap
